
@host=http://localhost:5001

@authorization=0FkVxU7XxRDeE6bsTOHhfWlIxFH0wmES63fk3CdTdX5Fs5ZDqY9WXYbreJxs2r42bRTvc1lHlAsTv4Yt98Gr4ILYkob4OTPSGxuBFfABBgr5bT6O7OPaqYBlZOAIuF3d

###
GET {{host}}/health

###
POST {{host}}/auth/sign-in
Content-Type: application/json

{
    "phone": "+573013819315"
}

###
POST {{host}}/auth/verification-code
Content-Type: application/json

{
    "phone": "+573013819315",
    "code": "I6MwEV"
}

###
GET {{host}}/auth/session
Content-Type: application/json
Authorization: Bearer {{authorization}}


###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "rol": "seller"
}

###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "rol": "client"
}

###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "name": "julio",
    "last_name": "torres"
}

###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "phone": "julio"
}

###
POST {{host}}/shops
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "identify": "onnasoft",
    "name": "Onnasoft",
    "description": "Consultora de software"
}

###
POST {{host}}/shops
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "identify": "onnasoft2",
    "name": "Onnasoft2",
    "description": "Consultora de software"
}

###
GET {{host}}/shops
Content-Type: application/json
Authorization: Bearer {{authorization}}

###
GET {{host}}/shops/me
Content-Type: application/json
Authorization: Bearer {{authorization}}


###
GET {{host}}/qr-code/generate
Content-Type: application/json
Authorization: Bearer {{authorization}}

###
POST {{host}}/products
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "sku": "carro",
    "name": "Carro",
    "description": "carro ultimo modelo",
    "shop_id": 1,
    "price": 10000000
}

###
GET {{host}}/products
Authorization: Bearer {{authorization}}

###
PATCH {{host}}/products/5
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "sku": "carro",
    "name": "Carro2",
    "description": "carro ultimo modelo"
}

###
POST {{host}}/user-shops-accounts/subscribe
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "shop_id": 1
}

###
POST {{host}}/user-shops-accounts/add-balance
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "shop_id": 1,
    "balance": 50000000,
    "client_id": 1
}

###
POST {{host}}/user-shops-accounts/buy
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "shop_id": 1,
    "quantity": 1,
    "product_id": 2
}
