
@host=http://localhost:5001

@authorization=TjMSxD4OlBNjBv3wo5i5KHflrOnrPoTXfWuy6RDnvTKhZex4zUcWU2iULgtthCo8bt55vsMSfGgLaSTovusRYciDj4mauQroiOHphGUUfCmZKP2CQNpsaMYQOxfkyWxs

###
GET {{host}}/health

###
POST {{host}}/auth/sign-in
Content-Type: application/json

{
    "phone": "+573013819315"
}

###
POST {{host}}/auth/verification-code
Content-Type: application/json

{
    "phone": "+573013819315",
    "code": "z2CwCU"
}

###
GET {{host}}/auth/session
Content-Type: application/json
Authorization: Bearer {{authorization}}


###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "rol": "seller"
}

###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "name": "julio",
    "last_name": "torres"
}

###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "phone": "julio"
}

###
POST {{host}}/shops
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "identify": "onnasoft",
    "name": "Onnasoft",
    "description": "Consultora de software"
}

###
POST {{host}}/shops
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "identify": "onnasoft2",
    "name": "Onnasoft2",
    "description": "Consultora de software"
}

###
GET {{host}}/shops
Content-Type: application/json
Authorization: Bearer {{authorization}}

###
GET {{host}}/shops/me
Content-Type: application/json
Authorization: Bearer {{authorization}}
