
@host=http://localhost:5001

@authorization=StYcYXjNhN2ofxRzyNXo5s8c1oqOEXcT0QDTrqtPhuj7bju1wE2xP5gI6vLep6MYfyHn9hhiaRTeOF8R3DNix7774yX4iJc0RPffZ52uFAgBTtgGC3go3iTn8CtVR0z8

###
GET {{host}}/health

###
POST {{host}}/auth/sign-in
Content-Type: application/json

{
    "phone": "+573013819315"
}

###
POST {{host}}/auth/verification-code
Content-Type: application/json

{
    "phone": "+573013819315",
    "code": "z2CwCU"
}

###
GET {{host}}/auth/session
Content-Type: application/json
Authorization: Bearer {{authorization}}


###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "rol": "seller"
}

###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "name": "julio",
    "last_name": "torres"
}

###
PATCH {{host}}/users/profile
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "phone": "julio"
}

###
POST {{host}}/shops
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "identify": "onnasoft",
    "name": "Onnasoft",
    "description": "Consultora de software"
}

###
POST {{host}}/shops
Content-Type: application/json
Authorization: Bearer {{authorization}}

{
    "identify": "onnasoft2",
    "name": "Onnasoft2",
    "description": "Consultora de software"
}

###
GET {{host}}/shops
Content-Type: application/json
Authorization: Bearer {{authorization}}

###
GET {{host}}/shops/me
Content-Type: application/json
Authorization: Bearer {{authorization}}


###
GET {{host}}/qr-code/generate
Content-Type: application/json
Authorization: Bearer {{authorization}}

